import type { CommentItem, LeaderboardItem, Question } from './types';

export const demoQuestions: Question[] = [
  {
    id: 9001,
    content: 'Theo truyền thuyết, Thánh Gióng đã nhổ loại cây gì để đánh giặc Ân?',
    option_A: 'Cây tre',
    option_B: 'Cây mía',
    option_C: 'Cây cau',
    option_D: 'Cây dừa',
    difficulty: 1,
  },
  {
    id: 9002,
    content: 'Đâu là tên một loại nhạc cụ truyền thống của Việt Nam?',
    option_A: 'Guitar',
    option_B: 'Piano',
    option_C: 'Đàn bầu',
    option_D: 'Violin',
    difficulty: 2,
  },
  {
    id: 9003,
    content: 'Ca dao Việt Nam ví công lao của người cha như điều gì?',
    option_A: 'Rừng Trà My',
    option_B: 'Biển Thái Bình',
    option_C: 'Sông Cửu Long',
    option_D: 'Núi Thái Sơn',
    difficulty: 3,
  },
  {
    id: 9004,
    content: 'Bộ phận nào trên cơ thể thằn lằn có khả năng mọc lại sau khi bị đứt?',
    option_A: 'Đầu',
    option_B: 'Cổ',
    option_C: 'Đuôi',
    option_D: 'Mắt',
    difficulty: 4,
  },
  {
    id: 9005,
    content: 'Hiện tượng rung chuyển vỏ Trái Đất được gọi là gì?',
    option_A: 'Địa chính',
    option_B: 'Địa chấn',
    option_C: 'Địa ngục',
    option_D: 'Địa đạo',
    difficulty: 5,
  },
  {
    id: 9006,
    content: 'Tỉnh nào sau đây có diện tích tự nhiên lớn hơn cả?',
    option_A: 'Thanh Hóa',
    option_B: 'Sơn La',
    option_C: 'Tây Ninh',
    option_D: 'Nghệ An',
    difficulty: 6,
  },
  {
    id: 9007,
    content: 'Ligue 1 là giải vô địch bóng đá cấp độ cao nhất của nước nào?',
    option_A: 'Pháp',
    option_B: 'Đức',
    option_C: 'Anh',
    option_D: 'Hà Lan',
    difficulty: 7,
  },
  {
    id: 9008,
    content: 'Phong cách kiến trúc nào nổi bật với vòm nhọn và cửa sổ kính màu lớn?',
    option_A: 'Gothic',
    option_B: 'Baroque',
    option_C: 'Renaissance',
    option_D: 'Romanesque',
    difficulty: 8,
  },
  {
    id: 9009,
    content: 'Đâu không phải là một trong Tứ đại phát minh của Trung Quốc cổ đại?',
    option_A: 'La bàn',
    option_B: 'Thuốc súng',
    option_C: 'Đồng hồ nước',
    option_D: 'Giấy',
    difficulty: 9,
  },
  {
    id: 9010,
    content: 'Làng Kim Bồng ở Hội An có nghề truyền thống là gì?',
    option_A: 'Làm đèn lồng',
    option_B: 'Trồng rau',
    option_C: 'Làm mộc',
    option_D: 'Làm gốm',
    difficulty: 10,
  },
  {
    id: 9011,
    content: 'Trong bài Côn Sơn ca, Nguyễn Trãi đã ví tiếng suối như tiếng gì?',
    option_A: 'Tiếng sáo diều',
    option_B: 'Tiếng chuông chùa',
    option_C: 'Tiếng đàn cầm',
    option_D: 'Tiếng trống hội',
    difficulty: 11,
  },
  {
    id: 9012,
    content: 'Nghệ thuật Pháp Lam phát triển rực rỡ nhất dưới triều đại nào?',
    option_A: 'Triều Lý',
    option_B: 'Triều Nguyễn',
    option_C: 'Triều Lê',
    option_D: 'Triều Trần',
    difficulty: 12,
  },
  {
    id: 9013,
    content: 'Thành phố cổ Petra từng là thủ đô của vương quốc cổ đại nào?',
    option_A: 'Phoenician',
    option_B: 'Byzantine',
    option_C: 'Ottoman',
    option_D: 'Nabataeans',
    difficulty: 13,
  },
  {
    id: 9014,
    content: 'Tên gọi của virus Nipah bắt nguồn từ đâu?',
    option_A: 'Tên một con sông',
    option_B: 'Tên một ngôi làng',
    option_C: 'Tên một loài cây bản địa',
    option_D: 'Tên một loài dơi',
    difficulty: 14,
  },
  {
    id: 9015,
    content: 'Câu nói về xây dựng đất nước đàng hoàng hơn, to đẹp hơn nằm trong văn kiện nào?',
    option_A: 'Lời kêu gọi đồng bào và chiến sĩ cả nước',
    option_B: 'Lời kêu gọi toàn quốc kháng chiến',
    option_C: 'Di chúc',
    option_D: 'Đường Kách mệnh',
    difficulty: 15,
  },
];

export const demoLeaderboard: LeaderboardItem[] = [
  { username: 'nora123', correct_count: 12 },
  { username: 'An', correct_count: 11 },
  { username: 'Binh', correct_count: 9 },
  { username: 'Chi', correct_count: 8 },
];

export const demoComments: CommentItem[] = [
  {
    name: 'Nguyễn Văn A',
    content: 'Bộ câu hỏi rõ ràng, nhịp chơi nhanh.',
    rating: 5,
    created_at: new Date().toISOString(),
  },
];
